POST http://node-zero-jt4o.onrender.com/videos
Content-Type: application/json


{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://node-zero-jt4o.onrender.com/videos

###

PUT http://node-zero-jt4o.onrender.com/videos
Content-Type: application/json


{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://node-zero-jt4o.onrender.com/videos/7104d76a-8abb-4256-a245-752fadd0dfdc